  

name: CI - Main
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        docker build -t openmc_data_to_json .
        docker run --rm openmc_data_to_json /bin/bash -c "pytest tests"
