  

name: CI - Main
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openmc/openmc:latest
   
    steps:
    - uses: actions/checkout@v3
    - name: install and test
      run: |
        pip install .
        pytest tests
